---
        - name: Enable ufw 
          ufw:
            state: enabled
            logging: 'on'
        - name: Allow OpenSSH on ufw
          ufw:
            rule: allow
            name: OpenSSH
        - name: Allow Apache 80 and 443 on ufw
          ufw:
            rule: allow
            name: "Apache Full" 