- name: start the Laravel Server Playbook
  hosts: all
  become: yes
  vars_files:
     - vars/default.yml
  vars_prompt:
    - name: database_option
      prompt: "Do you want to install MySQL (Y/N)"
      default: "N"
      private: no  
  roles: 
     - System
     - Apache
     - { role: Database, when: database_option == "Y" or database_option == "y" }
     - PHP
     - Composer
     - SSL
     - Firewall

  handlers:
     - name: restart apache2
       service: name=apache2 state=restarted
     - name: stop mysql-server
       service: name=mysql state=stopped