---
        - name: Enable ufw 
          ufw:
            state: enabled
            logging: 'on'
        - name: Allow OpenSSH on ufw
          ufw:
            rule: allow
            name: OpenSSH
        - name: Allow http80
          ufw:
            rule: allow
            port: '80'
        - name: Allow https443
          ufw:
            rule: allow
            port: '443'