---
        - name: Install MySQL-DB-SERVER
          apt: 
            name: mysql-server
            update_cache: true 
            force_apt_get: true
            state: present
          notify: stop mysql-server