--- 
        - name: Create SSH-Key using ssh-keygen for ubuntu user
          user:
            name: ubuntu
            generate_ssh_key: yes
            ssh_key_bits: 4096
            ssh_key_file: .ssh/id_rsa

        - name: Set system timezone to Asia/Kolkata
          timezone: 
            name: Asia/Kolkata
        - name: Install system packages through APT
          apt: 
            name: "{{ item }}"
            update_cache: true 
            force_apt_get: true
            state: present
          with_items:
              - 'git'
              - 'ufw'
              - 'curl'
              - 'zip'
              - 'apt-transport-https'
              - 'software-properties-common'
              - 'htop'
              - 'build-essential'