---
        - name: Install MySQL
          apt: 
            name: "{{ item }}"
            update_cache: true 
            force_apt_get: true
            state: present
          with_items:
              - 'mysql-server'
              - 'mysql-client'