- name: start the Server Playbook
  hosts: all
  become: yes
  vars_files:
     - vars/default.yml 
  roles: 
     - System
     - Apache
     - SSL
     - Firewall
  handlers:
     - name: restart apache2
       service: name=apache2 state=restarted

